//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not Found")]
        public string Status404 {
            get {
                return ((string)(this["Status404"]));
            }
            set {
                this["Status404"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Method Not Allowed")]
        public string Status405 {
            get {
                return ((string)(this["Status405"]));
            }
            set {
                this["Status405"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Continue")]
        public string Status100 {
            get {
                return ((string)(this["Status100"]));
            }
            set {
                this["Status100"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Switching Protocols")]
        public string Status101 {
            get {
                return ((string)(this["Status101"]));
            }
            set {
                this["Status101"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Processing")]
        public string Status102 {
            get {
                return ((string)(this["Status102"]));
            }
            set {
                this["Status102"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OK")]
        public string Status200 {
            get {
                return ((string)(this["Status200"]));
            }
            set {
                this["Status200"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Created")]
        public string Status201 {
            get {
                return ((string)(this["Status201"]));
            }
            set {
                this["Status201"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Accepted")]
        public string Status202 {
            get {
                return ((string)(this["Status202"]));
            }
            set {
                this["Status202"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Non-Authoritative Information")]
        public string Status203 {
            get {
                return ((string)(this["Status203"]));
            }
            set {
                this["Status203"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No Content")]
        public string Status204 {
            get {
                return ((string)(this["Status204"]));
            }
            set {
                this["Status204"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reset Content")]
        public string Status205 {
            get {
                return ((string)(this["Status205"]));
            }
            set {
                this["Status205"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Partial Content")]
        public string Status206 {
            get {
                return ((string)(this["Status206"]));
            }
            set {
                this["Status206"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Multi-Status")]
        public string Status207 {
            get {
                return ((string)(this["Status207"]));
            }
            set {
                this["Status207"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Multiple Choices")]
        public string Status300 {
            get {
                return ((string)(this["Status300"]));
            }
            set {
                this["Status300"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Moved Permanently")]
        public string Status301 {
            get {
                return ((string)(this["Status301"]));
            }
            set {
                this["Status301"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Found")]
        public string Status302 {
            get {
                return ((string)(this["Status302"]));
            }
            set {
                this["Status302"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("See Other")]
        public string Status303 {
            get {
                return ((string)(this["Status303"]));
            }
            set {
                this["Status303"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not Modified")]
        public string Status304 {
            get {
                return ((string)(this["Status304"]));
            }
            set {
                this["Status304"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Use Proxy")]
        public string Status305 {
            get {
                return ((string)(this["Status305"]));
            }
            set {
                this["Status305"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Switch Proxy")]
        public string Status306 {
            get {
                return ((string)(this["Status306"]));
            }
            set {
                this["Status306"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Temporary Redirect")]
        public string Status307 {
            get {
                return ((string)(this["Status307"]));
            }
            set {
                this["Status307"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bad Request")]
        public string Status400 {
            get {
                return ((string)(this["Status400"]));
            }
            set {
                this["Status400"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unauthorized")]
        public string Status401 {
            get {
                return ((string)(this["Status401"]));
            }
            set {
                this["Status401"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Payment Required")]
        public string Status402 {
            get {
                return ((string)(this["Status402"]));
            }
            set {
                this["Status402"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Forbidden")]
        public string Status403 {
            get {
                return ((string)(this["Status403"]));
            }
            set {
                this["Status403"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not Acceptable")]
        public string Status406 {
            get {
                return ((string)(this["Status406"]));
            }
            set {
                this["Status406"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proxy Authentication Required")]
        public string Status407 {
            get {
                return ((string)(this["Status407"]));
            }
            set {
                this["Status407"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Request Timeout")]
        public string Status408 {
            get {
                return ((string)(this["Status408"]));
            }
            set {
                this["Status408"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Conflict")]
        public string Status409 {
            get {
                return ((string)(this["Status409"]));
            }
            set {
                this["Status409"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gone")]
        public string Status410 {
            get {
                return ((string)(this["Status410"]));
            }
            set {
                this["Status410"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Length Required")]
        public string Status411 {
            get {
                return ((string)(this["Status411"]));
            }
            set {
                this["Status411"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Precondition Failed")]
        public string Status412 {
            get {
                return ((string)(this["Status412"]));
            }
            set {
                this["Status412"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Request Entity Too Large")]
        public string Status413 {
            get {
                return ((string)(this["Status413"]));
            }
            set {
                this["Status413"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Request-URI Too Long")]
        public string Status414 {
            get {
                return ((string)(this["Status414"]));
            }
            set {
                this["Status414"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unsupported Media Type")]
        public string Status415 {
            get {
                return ((string)(this["Status415"]));
            }
            set {
                this["Status415"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Requested Range Not Satisfiable")]
        public string Status416 {
            get {
                return ((string)(this["Status416"]));
            }
            set {
                this["Status416"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Expectation Failed")]
        public string Status417 {
            get {
                return ((string)(this["Status417"]));
            }
            set {
                this["Status417"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I\'m a teapot")]
        public string Status418 {
            get {
                return ((string)(this["Status418"]));
            }
            set {
                this["Status418"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unprocessable Entity")]
        public string Status422 {
            get {
                return ((string)(this["Status422"]));
            }
            set {
                this["Status422"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Locked")]
        public string Status423 {
            get {
                return ((string)(this["Status423"]));
            }
            set {
                this["Status423"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed Dependency")]
        public string Status424 {
            get {
                return ((string)(this["Status424"]));
            }
            set {
                this["Status424"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unordered Collection")]
        public string Status425 {
            get {
                return ((string)(this["Status425"]));
            }
            set {
                this["Status425"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Upgrade Required")]
        public string Status426 {
            get {
                return ((string)(this["Status426"]));
            }
            set {
                this["Status426"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Retry With")]
        public string Status449 {
            get {
                return ((string)(this["Status449"]));
            }
            set {
                this["Status449"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blocked by Windows Parental Controls")]
        public string Status450 {
            get {
                return ((string)(this["Status450"]));
            }
            set {
                this["Status450"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Internal Server Error")]
        public string Status500 {
            get {
                return ((string)(this["Status500"]));
            }
            set {
                this["Status500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not Implemented")]
        public string Status501 {
            get {
                return ((string)(this["Status501"]));
            }
            set {
                this["Status501"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bad Gateway")]
        public string Status502 {
            get {
                return ((string)(this["Status502"]));
            }
            set {
                this["Status502"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Service Unavailable")]
        public string Status503 {
            get {
                return ((string)(this["Status503"]));
            }
            set {
                this["Status503"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gateway Timeout")]
        public string Status504 {
            get {
                return ((string)(this["Status504"]));
            }
            set {
                this["Status504"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HTTP Version Not Supported")]
        public string Status505 {
            get {
                return ((string)(this["Status505"]));
            }
            set {
                this["Status505"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Variant Also Negotiates")]
        public string Status506 {
            get {
                return ((string)(this["Status506"]));
            }
            set {
                this["Status506"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Insufficient Storage")]
        public string Status507 {
            get {
                return ((string)(this["Status507"]));
            }
            set {
                this["Status507"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bandwidth Limit Exceeded")]
        public string Status509 {
            get {
                return ((string)(this["Status509"]));
            }
            set {
                this["Status509"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not Extended")]
        public string Status510 {
            get {
                return ((string)(this["Status510"]));
            }
            set {
                this["Status510"] = value;
            }
        }
    }
}
